### ISSUE TITLE
Tables in numbered lists are not rendered.

### ISSUE THREAD

**Issue by data-henrik** [IBM/marked-it#26]
I have trouble with tables in the middle of numbered lists. Either it breaks the table or the numbering.

```
1. Something like this does not work. Either the table is not rendered or the next numbered item restarts at 1.

   | Parameter     | Value                                                    |
   |---------------|----------------------------------------------------------|
   | Organization ID | Find this value under your USER NAME on the TOP ribbon |
   | Device Type     | simulator |
   | Device ID       | phone    |
   | Authentication Token | myauthtoken |

2. Your phone will start transmitting data. 
```

**Comment by grant-g** [comment]
This is what the underlying marked package intentionally generates in order to best respect the original (admittedly loose) markdown spec.  You're not the first to request this, and this is not unique to marked-based generators.

Keeping this request open in case the tool moves to a different underlying generator package that does not stick to the spec as closely.  However in the meantime if you really want to do this then you may need a hack that involves some mix of html and .md, like https://superuser.com/a/1289926.

**Comment by jenschlot** [comment]
This is now supported in marked-it 2.0.
